name: Deploy

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.20
        env:
          POSTGRES_DB: nfs-mirrorbot
          POSTGRES_PASSWORD: apasih
          POSTGRES_PORT: 5432
          POSTGRES_USER: nfs86
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: clone source
        run: |
          git clone https://AnGgIt88:$GH_TOKEN@github.com/AnGgIt88/mirror-leech-telegram-bot
        env:
         GH_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Deploy..
        run: |
          cd mirror-leech-telegram-bot
          sudo docker build . -t mirror-bot
          sudo docker run -p 80:80 mirror-bot
